apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy  # "myuser" codificado en base64
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # "mypassword" codificado en base64